[package]
name = "raspy-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "0.6"
warp = "0.3.2"
tokio = { version = "1.17.0", features = ["full"] }